export const RECEIVING_RESULT = "RECEIVING_RESULT";
export const RECEIVED_RESULT = "RECEIVED_RESULT";
export const RECEIVE_RESULT_ERROR = "RECEIVE_RESULT_ERROR";

export const TYPING = "TYPING";
export const TYPING_ERROR = "TYPING_ERROR";
